# Generated by Django 3.0 on 2020-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191230_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
